# Position of the UAV
float64 north
float64 east
float64 up

# Velocity of the UAV:
float64 v_north
float64 v_east
float64 v_up

# Vertical acceleration:
float64 acc_up

# Total velocity:
float64 v_tot

# Total acceleration:
float64 acc_tot

# COurse from the North:
float64 course
float64 fpa
float64 roll

# FLight characteristiccs:
float64 angle_attack
float64 sideslip

# Angular speed in the body frame:
float64 r
float64 q
float64 p

# Angular acceleration:
float64 r_dot
float64 p_dot
float64 q_dot

